routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login',['uses' => 'AdminController@login', 'as' => 'admin.login']);
Route::post('/admin/logout',['uses' => 'AdminController@logout', 'as' => 'admin.logout']);

Route::group(['prefix' => '/admin', 'middleware' => 'auth' ], function () {
    Route::get('dashboard',['uses' => 'AdminController@index', 'as' => 'admin.dashboard']);

    Route::resource('car','CarController',['as' => 'admin']);
    Route::get('/car/{car_id}/clone','CarController@clone')->name('admin.car.clone');

    Route::resource('brand','BrandController',['as' => 'admin']);
    Route::get('/brand/{brand_slug}/clone','BrandController@clone')->name('admin.brand.clone');

    Route::resource('user','UserController',['as' => 'admin']);
    Route::resource('contact', 'ContactController', ['as' => 'admin']);
});


Route::get('/',['uses' => 'FrontendController@index', 'as' => 'home']);
Route::get('/contact-us',['uses' => 'FrontendController@contact', 'as' => 'contact']);
Route::get('car/filter',['uses' => 'FrontendController@filter', 'as' => 'filter']);
Route::get('car/search',['uses' => 'FrontendController@searchCarName', 'as' => 'searchCarName']);
Route::get('/car/brand/{slug}', ['uses' => 'FrontendController@carByBrand', 'as' => 'brand']);
Route::get('/car/{slug}',['uses' => 'FrontendController@carDetail', 'as' => 'detail']);



// Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/fragments/footer.blade.php
<footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © {{config('app.name','BookStore')}} 2018</small>
        </div>
      </div>
</footer>

resources/views/admin/fragments/head.blade.php
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- Bootstrap core CSS-->
<link href="{{asset('adminAssets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
<!-- Custom fonts for this template-->
<link href="{{asset('adminAssets/vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
<!-- Page level plugin CSS-->
<link href="{{asset('adminAssets/vendor/datatables/dataTables.bootstrap4.css')}}" rel="stylesheet">
<!-- Custom styles for this template-->
<link href="{{asset('adminAssets/css/sb-admin.css')}}" rel="stylesheet">

<link href="{{asset('adminAssets/css/custom.css')}}" rel="stylesheet">

resources/views/admin/fragments/header.blade.php
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{{route('admin.dashboard')}}">{{config('app.name','CarStore')}}</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{route('admin.dashboard')}}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
          <a class="nav-link" href="{{route('admin.car.index')}}">
            <i class="fa fa-fw fa-car"></i>
            <span class="nav-link-text">Cars</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{route('admin.brand.index')}}">
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">Car Brand</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
            <a class="nav-link" href="{{route('admin.user.index')}}">
              <i class="fa fa-fw fa-users"></i>
              <span class="nav-link-text">Users</span>
            </a>
          </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{route('admin.contact.index')}}">
            <i class="fa fa-fw fa-phone"></i>
            <span class="nav-link-text">Contact</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
          <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
              <i class="fa fa-fw fa-angle-left"></i>
            </a>
          </li>
        </ul>
      </div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }} <span class="caret"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        
                <a class="dropdown-item" href="{{ route('admin.logout') }}"
                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                    <i class="fa fa-fw fa-sign-out"></i>{{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
      </ul>
  </nav>

resources/views/admin/fragments/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<title>
    {{config('app.name','BookStore')}}
</title>
@include('admin.fragments.head')
</head>
<body>
<div class="fixed-nav sticky-footer bg-dark" id="page-top">
    @include('admin.fragments.header')
    
    <div class="content-wrapper pt-4">
        <div class="container-fluid mt-5">
            @yield('breadcrumb')
        </div>

        <div class="container-fluid">
            @include('admin.fragments.message')
        </div>

        @yield('content')
    </div>

    @include('admin.fragments.footer')
</div>
</body>
@include('admin.fragments.scripts')

resources/views/admin/fragments/message.blade.php
@if(isset($errors) && count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{$error}}
        </div>
    @endforeach
@endif

@if(session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{session('error')}}
    </div>
@endif

resources/views/admin/fragments/scripts.blade.php
<script src="{{asset('admin/vendor/jquery/jquery.min.js')}}"></script>

<script src="{{asset('admin/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- Core plugin JavaScript-->
<script src="{{asset('admin/vendor/jquery-easing/jquery.easing.min.js')}}"></script>
<!-- Page level plugin JavaScript-->
{{-- <script src="{{asset('admin/vendor/chart.js/Chart.min.js')}}"></script> --}}
<script src="{{asset('admin/vendor/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/vendor/datatables/dataTables.bootstrap4.js')}}"></script>
<!-- Custom scripts for all pages-->
<script src="{{asset('admin/js/sb-admin.min.js')}}"></script>
<!-- Custom scripts for this page-->
<script src="{{asset('admin/js/sb-admin-datatables.min.js')}}"></script>
{{-- <script src="{{asset('admin/js/sb-admin-charts.min.js')}}"></script> --}}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script src="{{asset('admin/js/custom.js')}}"></script>

<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<script>
    $(document).ready(function() {
        $('#summernote').summernote({
            placeholder:    'Add more information...',
            height: 200,
        });
    });
  </script>