routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login',['uses' => 'AdminController@login', 'as' => 'admin.login']);
Route::post('/admin/logout',['uses' => 'AdminController@logout', 'as' => 'admin.logout']);

Route::group(['prefix' => '/admin', 'middleware' => 'auth' ], function () {
    Route::get('dashboard',['uses' => 'AdminController@index', 'as' => 'admin.dashboard']);

    Route::resource('car','CarController',['as' => 'admin']);
    Route::get('/car/{car_id}/clone','CarController@clone')->name('admin.car.clone');

    Route::resource('brand','BrandController',['as' => 'admin']);
    Route::get('/brand/{brand_slug}/clone','BrandController@clone')->name('admin.brand.clone');

    Route::resource('user','UserController',['as' => 'admin']);
    Route::resource('contact', 'ContactController', ['as' => 'admin']);
});


Route::get('/',['uses' => 'FrontendController@index', 'as' => 'home']);
Route::get('/contact-us',['uses' => 'FrontendController@contact', 'as' => 'contact']);
Route::get('car/filter',['uses' => 'FrontendController@filter', 'as' => 'filter']);
Route::get('car/search',['uses' => 'FrontendController@searchCarName', 'as' => 'searchCarName']);
Route::get('/car/brand/{slug}', ['uses' => 'FrontendController@carByBrand', 'as' => 'brand']);
Route::get('/car/{slug}',['uses' => 'FrontendController@carDetail', 'as' => 'detail']);



// Route::get('/home', 'HomeController@index')->name('home');

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Car;

class Brand extends Model
{
    public function cars(){
        return $this->hasMany(Car::class);
    }

    public function countCar(){
        return $this->cars()->where('status',1)->count();
    }

    public function getAmountOfCars($number){
        return $this->cars()->take($number)->get();
    }

}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use Illuminate\Http\Request;
use \Illuminate\Database\Eloquent\ModelNotFoundException;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $size =$request->input('size');
        if(!$size){
            $size = 10   ;
        }

        $sort = $request->input('sort');
        $order = $request->input('order');
        if($sort && $order){
            $brands = Brand::orderBy($sort,$order);
        }else{
            $brands = Brand::orderBy('created_at','desc');
        }

        $brand_name = $request->input('brand_name');
        $brand_status = $request->input('brand_status');
        if($brand_name){
            $brands->where('name','LIKE','%'.$brand_name.'%');
        }
        if($brand_status){
            if($brand_status != 'all'){
                $brands->where('status',$brand_status == "enable" ? 1 : 0);
            }
        }
        
        $brands = $brands->paginate($size);
        return view('admin.brand.index')->with([
            'brands' => $brands,
            'size' => $size,
            'brand_name' => $brand_name,
            'brand_status' => $brand_status,
            'sort' => $sort,
            'order' => $order
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.brand.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'slug' => 'required | unique:brands,slug'
        ]);

        $brand = new Brand;
        $brand->name = $request->input('name');
        $brand->slug = $request->input('slug');
        $brand->status = $request->input('status') ? 1 : 0;
        $brand->save();
        
        if($request->input('save_continue')){
            return redirect()->route('admin.brand.create')->with([
                'success' => $brand->name . " brand is successfully created."
            ]);
        }

        return redirect()->route('admin.brand.index')->with([
            'success' => $brand->name  . ' brand is successfully created.'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $brand = Brand::where('slug',$slug)->first();

        if(!$brand){
            throw new ModelNotFoundException;
        }
        return view('admin.brand.create')->with([
            'brand' => $brand
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $brand = Brand::find($id);
        
        $this->validate($request,[
            'name' => 'required',
            'slug' => 'required | unique:brands,slug,'.$id
        ]);
       
        $brand->name = $request->input('name');
        $brand->slug = $request->input('slug');
        $brand->status = $request->input('status') == "on" ? 1 : 0;
        $brand->save();

        return redirect()->route('admin.brand.index')->with([
            'success' => $brand->name . " brand has been successfully updated."
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $brand = Brand::findOrFail($id);
        $name = $brand->name;
        $brand->cars()->delete();
        $brand->delete();

        return redirect()->route('admin.brand.index')->with([
            'success' => $name . ' brand has been successfuly deleted.'
        ]);
    }

    public function clone($slug){
        $brand = Brand::where('slug',$slug)->first();

        if(!$brand){
            throw new ModelNotFoundException;
        }

        return view('admin.brand.create')->with([
            'brand' => $brand,
            'clone' => 'clone'
        ]);
    }
}

resources/views/admin/brand/create.blade.php
@extends('admin.fragments.master')

<!-- Breadcrumbs-->
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{route('admin.brand.index')}}">Car Brand</a></li>
        <li class="breadcrumb-item active">{{isset($brand) && $brand ? $brand->name . " / Edit" : "New"}}</li>
    </ol>
@endsection

@section('content')
<div class="container-fluid pb-4">

    <div class="card">
        <div class="card-header">
            <strong>{{isset($brand) && $brand ? "Edit brand " : "New Book"}}  
           
        </div>
        
        <div class="card-body">      
            {!!Form::open(['route' => isset($brand) && $brand && !isset($clone) ? ["admin.brand.update",$brand->id] : 'admin.brand.store', 'method' => 'POST', 'class' => 'form-inline'])!!}       
            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left pl-0">
                  {!!Form::label('name','Brand Name *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9"> 
                  {!!Form::text('name',isset($brand) && $brand ? $brand->name : "",['class' => 'form-control w-100 brand-name', 'placeholder' => 'Brand Name'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left pl-0">
                  {!!Form::label('slug','Slug Name *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9"> 
                  {!!Form::text('slug',isset($brand) && $brand ? $brand->slug : "",['class' => 'form-control w-100 brand-slug', 'placeholder' => 'Slug Name'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
                <div class="col-md-3 text-left pl-0">
                  {!!Form::label('status','Brand Status',['class' => 'justify-content-start'])!!}
                </div>
                 <div class="col-md-9"> 
                    <label class="switch">
                        <input name="status" type="checkbox" {{isset($brand) && $brand ? $brand->status ? "checked" : "" : "checked"}}>
                        <span class="slider"></span>
                        
                    </label>
                </div>
            </div>

        </div>
        <div class="card-footer">
            {{isset($brand) && $brand && !isset($clone) ? Form::hidden('_method','PUT') : ''}} 
            <a href="{{ route('admin.brand.index') }}" class="btn btn-danger text-white"><i class="fa fa-ban"></i> Cancel</a>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
           
            @if(!isset($brand) || isset($clone))
                <button id="save-continue" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save & Continue</button>
            @endif
        </div>
        {!!Form::close()!!}
      </div>    
       
</div>
@endsection

resources/views/admin/brand/index.blade.php
@extends('admin.fragments.master')

@section('breadcrumb')
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
        <li class="breadcrumb-item active">Car Brand</li>
    </ol>
@endsection

@section('content')
<div class="container-fluid pb-4">
    
    <div class="card mb-5">
        <div class="card-header">
          <a href="{{route('admin.brand.create')}}" class="btn btn-primary text-white"><i class="fa fa-plus"></i> New Brand</a>
        </div>
        <div class="card-body">
          
            <div class="row mb-3">
              <div class="col-sm-12 col-md-4">
                <div class="form-inline" >
                  <label>Show &nbsp; 
                    <select id="brand_size" name="size_table" class="form-control form-control-sm">
                      <option {{$size == 10 ? 'selected' : ''}} value="size=10">10</option>
                      <option {{$size == 25 ? 'selected' : ''}} value="size=25">25</option>
                      <option {{$size == 50 ? 'selected' : ''}} value="size=50">50</option>
                      <option {{$size == 100 ? 'selected' : ''}} value="size=100">100</option>
                    </select> &nbsp; entries
                  </label>
                </div>
              </div> 
              <div class="col-sm-12 col-md-8 text-right">
                <form class="form-inline" method="GET" action="{{route('admin.brand.index')}}">
                      <label class="sr-only" for="Brand">Brand Name</label>
                      <input type="text" name="brand_name" class="form-control mb-2 mr-sm-3" id="brand-name" placeholder="Brand name"
                              value="{{isset($brand_name) && $brand_name ? $brand_name : ''}}">
                      
                      <label class="sr-only" for="Brand">Brand Status</label>
                      <select id="brand-status" name="brand_status" class="form-control mb-2 mr-sm-3">
                          <option value="all">Select Status</option>
                          <option {{isset($brand_status) && $brand_status == "enable" ? 'selected'  : ''}} value="enable">Enable</option>
                          <option {{isset($brand_status) && $brand_status == "disable" ? 'selected' : ''}} value="disable">Disable</option>
                      </select> 
                    
                      <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i></button>
                    </form>
              </div>
            </div>
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Name <small><a href="sort=name&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('name')}}"></i></a></small></th>
                  <th>Status <small><a href="sort=status&order={{isset($order)?$order=='asc'?'desc':'asc' :'asc'}}" class="text-dark sort"><i class="fa {{getSortIcon('status')}}"></i></a></small></th>
                  <th>Car Count</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>No</th>
                  <th>Name</th>
                  <th>Status</th>
                  <th>Car Count</th>
                  <th>Action</th>
                </tr>
              </tfoot>
              <tbody>
                @if(isset($brands) && count($brands) > 0)
                    @foreach($brands as $key => $brand)
                        <tr>
                            <td class="text-center">{{$key + 1}}</td>
                            <td>{{$brand->name}}</td>
                            @if($brand->status == 1) 
                              <td class="text-center"><span class='badge badge-success'>Enabled</span></td>
                            @else 
                              <td class="text-center"><span class='badge badge-danger'>Disabled</span></td>
                            @endif
                            <td class="text-center h5"><span class=" badge badge-info">{{count($brand->cars)}}</span></td>
                            <td>
                                <a href="{{route('admin.brand.edit',$brand->slug)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                <a href="{{route('admin.brand.clone',$brand->slug)}}" class="btn btn-success btn-sm"><i class="fa fa-clone"></i></a>
                                {!!Form::open(['route' => ['admin.brand.destroy', $brand->id], 'method' => 'POST', 'class' => 'd-inline'])!!}
                                   {{Form::hidden('_method','DELETE')}}
                                   <button type="submit" data-id={{$brand->id}} class="btn btn-danger btn-sm btn-delete-brand" id="delete"><i class="fa fa-trash-o "></i></button>
                                 
                                {!!Form::close()!!}
                            </td>
                        </tr>
                    @endforeach
                @else
                  <td colspan="5">No data found</td>
                @endif
              </tbody>
            </table>
          </div>

          <span>Showing  {{ $brands->firstItem() }} - {{ $brands->lastItem() }} of {{$brands->total()}} entries,
          </span>
          Per page:
          <span class="text-dark">
            <a href="size=10" class="page text-dark {{$size == 10 ? 'font-weight-bold' : ''}}">10</a>, 
            <a href="size=25" class="page text-dark {{$size == 25 ? 'font-weight-bold' : ''}}">25</a>, 
            <a href="size=50" class="page text-dark {{$size == 50 ? 'font-weight-bold' : ''}}">50</a>,
            <a href="size=100" class="page text-dark {{$size == 100 ? 'font-weight-bold' : ''}}">100</a>
          </span>
          <div class="float-right">

                  @if ($brands->hasPages())
                      {{ $brands->links() }}
                  @endif
          </div>
        </div>
      </div>     
</div>
@endsection