routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/admin/login',['uses' => 'AdminController@login', 'as' => 'admin.login']);
Route::post('/admin/logout',['uses' => 'AdminController@logout', 'as' => 'admin.logout']);

Route::group(['prefix' => '/admin', 'middleware' => 'auth' ], function () {
    Route::get('dashboard',['uses' => 'AdminController@index', 'as' => 'admin.dashboard']);

    Route::resource('car','CarController',['as' => 'admin']);
    Route::get('/car/{car_id}/clone','CarController@clone')->name('admin.car.clone');

    Route::resource('brand','BrandController',['as' => 'admin']);
    Route::get('/brand/{brand_slug}/clone','BrandController@clone')->name('admin.brand.clone');

    Route::resource('user','UserController',['as' => 'admin']);
    Route::resource('contact', 'ContactController', ['as' => 'admin']);
});


Route::get('/',['uses' => 'FrontendController@index', 'as' => 'home']);
Route::get('/contact-us',['uses' => 'FrontendController@contact', 'as' => 'contact']);
Route::get('car/filter',['uses' => 'FrontendController@filter', 'as' => 'filter']);
Route::get('car/search',['uses' => 'FrontendController@searchCarName', 'as' => 'searchCarName']);
Route::get('/car/brand/{slug}', ['uses' => 'FrontendController@carByBrand', 'as' => 'brand']);
Route::get('/car/{slug}',['uses' => 'FrontendController@carDetail', 'as' => 'detail']);



// Route::get('/home', 'HomeController@index')->name('home');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Brand;

class Car extends Model
{
    public function brand(){
        return $this->belongsTo(Brand::class);
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Car;
use Illuminate\Http\Request;
use App\Brand;
use Intervention\Image\ImageManagerStatic as Image;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $brand_id = '';
        $size =$request->input('size');
        if(!$size){
            $size = 10   ;
        }

        $sort = $request->input('sort');
        $order = $request->input('order');
        if($sort && $order){
            if($sort == 'brand'){
                $cars = Car::orderBy('brands.name',$order)
                        ->join('brands','brands.id','=','cars.brand_id')
                        ->select('cars.*');
            }else{
                $cars = Car::orderBy($sort,$order);
            }
            
        }else{
            $cars = Car::orderBy('cars.created_at','desc');
        }

        $search = $request->input('search');
        $brand_slug = $request->input('car_brand');
        $car_status = $request->input('car_status');

        if($search){
             $cars->where(function($cars) use ($search){
                $cars->orWhere('cars.name','LIKE','%'.$search.'%')
                ->orWhere('cars.price',$search)
                ->orWhere('cars.model_year','LIKE', '%'.$search.'%');
                });
        }
        if($brand_slug!= null){
            if($brand_slug != 'all'){
                $brand = Brand::where('slug',$brand_slug)->first();
                $cars->where('brand_id',$brand->id);
            }   
        } 

        if($car_status != null){
            if($car_status != 'all'){
                $cars->where('cars.status',$car_status == "enable" ? 1 : 0);
             } 
        }    
        
        $cars = $cars->paginate($size);
        
        $brands = Brand::all();
        return view('admin.car.index')->with([
            'cars' => $cars,
            'brands' => $brands,  
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands = Brand::where('status',1)->orderBy('name','ASC')->pluck('name','id');
        
        return view('admin.car.create')->with([
            'brands' => $brands
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required',
            'slug' => 'unique:cars,slug',
            'price' => 'required | numeric',
            'model_year' => 'nullable | numeric',
            'image' => 'image | mimes:jpg,jpeg,png',
        ]);

        if($request->hasFile('image')){
            $image = $request->file('image');
            
            $imageNameWithExt = $image->getClientOriginalName();

            $imageName = pathInfo($imageNameWithExt,PATHINFO_FILENAME);

            $extension = $image->getClientOriginalExtension();

            $newImageName = $imageName.'_'.time().'.'.$extension;

            $pathImage = $image->storeAs('public/images',$newImageName);

            // Resize

            $thumbnailpath = public_path('storage/images/'.$newImageName);

            Image::make($thumbnailpath)->resize(400, 300)->save($thumbnailpath);

        }


        $car = new Car;
        $car->name = $request->input('name');
        $car->slug = $request->input('slug');
        $car->brand_id = $request->input('brand');
        $car->price = $request->input('price');
        $car->fuel_type = $request->input('fuel_type');
        $car->condition = $request->input('condition');
        $car->color = $request->input('color');
        $car->description = $request->input('description');
        $car->model_year = $request->input('model_year');
        if(isset($newImageName)){
            $car->image = $newImageName;
        }else if($request->input('image_clone')){
            $car->image   =  $request->input('image_clone');
        } 
        $car->status = $request->input('status') == "on" ? 1 : 0;
        $car->user_id = auth()->user()->id;

        $car->save();

        if($request->input('save_continue')){
            return redirect()->route('admin.car.create')->with([
                'success' => $car->name . " car has been created."
            ]);
        }

        return redirect()->route('admin.car.index')->with([
            'success' => $car->name . " car has been created."
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function show(Car $car)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        $brands = Brand::where('status',1)->orderBy('name','ASC')->pluck('name','id');
        
        $car = Car::where('slug',$slug)->first();

        return view('admin.car.create')->with([
            'car' => $car,
            'brands' => $brands
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required',
            'slug' => 'unique:cars,slug,'.$id,
            'price' => 'required | numeric',
            'model_year' => 'nullable | numeric',
            'image' => 'image | mimes:jpg,jpeg,png',
        ]);

        if($request->hasFile('image')){
            $image = $request->file('image');
            
            $imageNameWithExt = $image->getClientOriginalName();

            $imageName = pathInfo($imageNameWithExt,PATHINFO_FILENAME);

            $extension = $image->getClientOriginalExtension();

            $newImageName = $imageName.'_'.time().'.'.$extension;

            $pathImage = $image->storeAs('public/images',$newImageName);

            // Resize

            $thumbnailpath = public_path('storage/images/'.$newImageName);

            Image::make($thumbnailpath)->resize(400, 300)->save($thumbnailpath);

        }


        $car = Car::findOrFail($id);
        $car->name = $request->input('name');
        $car->slug = $request->input('slug');
        $car->brand_id = $request->input('brand');
        $car->price = $request->input('price');
        $car->fuel_type = $request->input('fuel_type');
        $car->condition = $request->input('condition');
        $car->color = $request->input('color');
        $car->description = $request->input('description');
        $car->model_year = $request->input('model_year');
        if(isset($newImageName)) $car->image = $newImageName;
        $car->status = $request->input('status') == "on" ? 1 : 0;
        $car->user_id = auth()->user()->id;

        $car->save();

        if($request->input('save_continue')){
            return redirect()->route('admin.car.create')->with([
                'success' => $car->name . " car has been updated."
            ]);
        }

        return redirect()->route('admin.car.index')->with([
            'success' => $car->name . " car has been updated."
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Car  $car
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $car = Car::findOrFail($id);
        $name = $car->title;
        $car->delete();

        return redirect()->route('admin.car.index')->with([
            'success' => $name . ' book has been successfuly deleted.'
        ]);
    }

    public function clone($slug){
        $brands = Brand::where('status',1)->orderBy('name','ASC')->pluck('name','id');

        $car = Car::where('slug',$slug)->first();

        return view('admin.car.create')->with([
            'car' => $car,
            'brands' => $brands,
            'clone' => 'clone'
        ]);
    }
}

resources/views/admin/car/create.blade.php
@extends('admin.fragments.master')

@section('breadcrumb')
<!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{route('admin.car.index')}}">Car</a></li>
        <li class="breadcrumb-item active">{{isset($car) && $car ? $car->name . " / Edit" : "New"}}</li>
    </ol>
@endsection

@section('content')
<div class="container-fluid pb-4">
    <div class="card mb-5">
        <div class="card-header">
          <strong>New Car</strong>  
        </div>
        <div class="card-body ">
          {!!Form::open(['route' => isset($car) && $car && !isset($clone) ? ['admin.car.update',$car->id] : 'admin.car.store', 'method' => 'POST', 'class' => 'form-inline', 'files' => true])!!}
            
            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('name','Name *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::text('name', isset($car) && $car ? $car->name : '',['class' => 'form-control w-100 car-name', 'placeholder' => 'Car Name'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('slug','Slug *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::text('slug', isset($car) && $car ? $car->slug : '',['class' => 'form-control w-100 car-slug', 'placeholder' => 'Slug Name'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('brand','Brand *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::select('brand', $brands, isset($car) && $car ? $car->brand->id : null ,['class' => 'form-control w-100'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('price','Price ($) *',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::number('price',isset($car) && $car ? $car->price : '',['class' => 'form-control w-100', 'placeholder' => '10000.00'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('model_year',' Model Year',['class' => 'justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::text('model_year',isset($car) && $car ? $car->model_year : '',['class' => 'form-control w-100', 'placeholder' => '2018'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
                <div class="col-md-3 text-left  pl-0 pr-0">
                    {!!Form::label('color','Color',['class' => 'justify-content-start'])!!}
                </div>
                <div class="col-md-9 pl-0 pr-0"> 
                    {!!Form::text('color',isset($car) && $car ? $car->color : '',['class' => 'form-control w-100', 'placeholder' => 'White | Black'])!!}
                </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
                <div class="col-md-3 text-left  pl-0 pr-0">
                    {!!Form::label('fuel_type','Fuel Type',['class' => 'justify-content-start'])!!}
                </div>
                <div class="col-md-9 pl-0 pr-0"> 
                    {!!Form::text('fuel_type',isset($car) && $car ? $car->fuel_type : '',['class' => 'form-control w-100', 'placeholder' => 'LPG | Petrol | Dissel ...'])!!}
                </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0 pl-0 pr-0">
                <div class="col-md-3 text-left  pl-0 pr-0">
                    {!!Form::label('condition','Condition',['class' => 'justify-content-start'])!!}
                </div>
                <div class="col-md-9 pl-0 pr-0"> 
                    {!!Form::text('condition',isset($car) && $car ? $car->condition : '',['class' => 'form-control w-100', 'placeholder' => 'New | Used'])!!}
                </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('extra_data','Extra Information',['class' => 'd-flex align-items-start justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                  {!!Form::textarea('description', isset($car) && $car ? $car->description : '', ['size' => '30x7','class' => 'form-control w-100', 'id' => 'summernote'])!!}
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left  pl-0 pr-0">
                  {!!Form::label('image','Image',['class' => 'd-flex justify-content-start'])!!}
              </div>
              <div class="col-md-9 pl-0 pr-0"> 
                <img id="image-upload" src="{{asset(isset($car->image)? 'storage/images/'.$car->image : 'assets/images/400x300.png')}}">
                @if(isset($clone))
                    <input hidden name="image_clone" type="text" value="{{$car->image}}">
                @else
                    <input hidden name="image" type="file" id="image">  
                @endif
                
              </div>
            </div>

            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
                <div class="col-md-3 text-left  pl-0 pr-0">
                    {!!Form::label('image','Image Gallery',['class' => 'd-flex justify-content-start'])!!}
                </div>
                <div class="col-md-9 pl-0 pr-0 increment"> 
                    <div class="block-gallery d-inline">
                        
                    </div>
                    <img id="image-gallery" src="{{asset('assets/images/add-more.jpg')}}">
                    <input name="image-gallery[]" id="image-gallery-input" type="file" multiple hidden>
                </div>
            </div>
            
            <div class="form-group col-md-12 mb-3 pl-0 pr-0">
              <div class="col-md-3 text-left pl-0 pr-0">
                  {!!Form::label('status','Status',['class' => 'justify-content-start'])!!}
                </div>
                 <div class="col-md-9 pl-0 pr-0"> 
                    <label class="switch">
                        <input name="status" type="checkbox" {{isset($car) && $car ? $car->status ? "checked" : "" : "checked"}}>
                        <span class="slider"></span>
                        
                    </label>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <a href="{{ route('admin.car.index') }}" class="btn btn-danger text-white"><i class="fa fa-ban"></i> Cancel</a>
            {{isset($car) && $car && !isset($clone)? Form::hidden('_method','PUT') : ''}} 
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
            @if(!isset($car) || isset($clone))
                <button id="save-continue" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save & Continue</button>
            @endif
        </div>
        {!!Form::close()!!}
      </div>     
</div>
@endsection

resources/views/admin/car/index.blade.php
@extends('admin.fragments.master')

@section('breadcrumb')
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}">Dashboard</a></li>
    <li class="breadcrumb-item active">Car</li>
</ol>
@endsection

@section('content')
<div class="container-fluid pb-4" id="car-list">
    <div class="card mb-5">
        <div class="card-header">
          <a href="{{route('admin.car.create')}}" class="btn btn-primary text-white"><i class="fa fa-plus"></i> New Car</a>
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-sm-12 col-md-4">
                  <div class="form-inline" >
                    <label>Show &nbsp; 
                      <select id="brand_size" name="size_table" class="form-control form-control-sm">
                        <option {{isset($_GET['size']) && $_GET['size'] == 10 ? 'selected' : ''}} value="size=10">10</option>
                        <option {{isset($_GET['size']) && $_GET['size'] == 25 ? 'selected' : ''}} value="size=25">25</option>
                        <option {{isset($_GET['size']) && $_GET['size'] == 50 ? 'selected' : ''}} value="size=50">50</option>
                        <option {{isset($_GET['size']) && $_GET['size'] == 100 ? 'selected' : ''}} value="size=100">100</option>
                      </select> &nbsp; entries
                    </label>
                  </div>
                </div> 
                <div class="col-sm-12 col-md-8 text-right">
                  <form class="form-inline" method="GET" action="{{route('admin.car.index')}}">
                        <label class="sr-only" for="car_name">car Title</label>
                        <input type="text" name="search" class="form-control mb-2 mr-sm-3" id="car-name" placeholder="Search for ..."
                                value="{{isset($_GET['search']) ? $_GET['search'] : ''}}">
                        
                        <label class="sr-only" for="status">Brand</label>
                        <select id="car-status" name="car_brand" class="form-control mb-2 mr-sm-3">
                            <option value="all">All Brand</option>
                            @foreach($brands as $brand)
                              <option {{isset($_GET['car_brand']) && $_GET['car_brand'] == $brand->slug ? 'selected' : ''  }} value="{{$brand->slug}}">{{$brand->name}}</option>  
                            @endforeach
                        </select> 

                        <label class="sr-only" for="status">Status</label>
                        <select id="car-status" name="car_status" class="form-control mb-2 mr-sm-3">
                            <option value="all">Status</option>
                            <option {{isset($_GET['car_status']) && $_GET['car_status'] == "enable" ? 'selected'  : ''}} value="enable">Enable</option>
                            <option {{isset($_GET['car_status']) && $_GET['car_status'] == "disable" ? 'selected' : ''}} value="disable">Disable</option>
                        </select> 
                      
                        <button type="submit" class="btn btn-primary mb-2"><i class="fa fa-search"></i></button>
                      </form>
                </div>
              </div>
          <div class="table-responsive">
            <table class="table table-bordered  table-hover">
              <thead>
                <tr>
                  <th>Image</th>
                  <th>Name <small class="d-none d-md-inline"><a href="sort=name&order={{isset($_GET['order'])?$_GET['order']=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('name')}}"></i></a></small></th>
                  <th>Brand <small class="d-none d-md-inline"><a href="sort=brand&order={{isset($_GET['order'])?$_GET['order']=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('brand')}}"></i></a></small></th>
                  <th>Price($) <small class="d-none d-md-inline"><a href="sort=price&order={{isset($_GET['order'])?$_GET['order']=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('price')}}"></i></a></small></th>
                  <th>Year <small class="d-none d-md-inline"><a href="sort=model_year&order={{isset($_GET['order'])?$_GET['order']=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('model_year')}}"></i></a></small></th>
                  <th>Condition <small class="d-none d-md-inline"><a href="sort=condition&order={{isset($_GET['order'])?$_GET['order']=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('condition')}}"></i></a></small></th>
                  <th>Status <small class="d-none d-md-inline"><a href="sort=status&order={{isset($_GET['order'])?$_GET['order']=='asc'?'desc':'asc' :'asc'}}"  class="text-dark sort"><i class="fa {{getSortIcon('status')}}"></i></a></small></th>
                  <th>Action</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Brand</th>
                  <th>Price($)</th>
                  <th>Year</th>
                  <th>Condition</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </tfoot>
              <tbody>
                @if(isset($cars) && count($cars) > 0)
                    @foreach($cars as $key => $car)
                        <tr>
                            <td class="text-center" style="width:100px">
                              @if($car->image)
                                <img width="100%" src="{{ asset('storage/images/'.$car->image)}}" alt="Image">
                              @else
                                <img width="100%" src="{{asset('assets/images/no_image.jpg')}}" alt="Image"> 
                              @endif
                            </td>
                            <td>{{$car->name}}</td>
                            <td>{{$car->brand->name}}</td>
                            <td>{{$car->price}}</td>
                            <td>{{$car->model_year}}</td>
                            <td class="text-center" style="width:120px;">{{$car->condition}}</td>
                            @if($car->status == 1) 
                              <td class="text-center"><span class='badge badge-success'>Enabled</span></td>
                            @else 
                              <td class="text-center"><span class='badge badge-danger'>Disabled</span></td>
                            @endif
                            <td>
                                <a href="{{route('admin.car.edit',$car->slug)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                <a href="{{route('admin.car.clone',$car->slug)}}" class="btn btn-success btn-sm"><i class="fa fa-clone"></i></a>
                                {!!Form::open(['route' => ['admin.car.destroy', $car->id], 'method' => 'POST', 'class' => 'd-inline'])!!}
                                   {{Form::hidden('_method','DELETE')}}
                                   <button type="submit" data-id={{$car->id}}  class="btn btn-danger btn-sm btn-delete-car" ><i class="fa fa-trash-o "></i></button>
                                 
                                {!!Form::close()!!}
                              </td>
                        </tr>
                    @endforeach
                @else
                  <td colspan="7">No data found</td>
                @endif
              </tbody>
            </table>
          </div>
          <span>Showing  {{ $cars->firstItem() }} - {{ $cars->lastItem() }} of {{$cars->total()}} entries,
            </span>
            Per page:
            <span class="text-dark">
              <a href="size=10" class="page text-dark {{!isset($_GET['size']) || $_GET['size'] == 10 ? 'font-weight-bold' : ''}}">10</a>, 
              <a href="size=25" class="page text-dark {{isset($_GET['size']) && $_GET['size'] == 25 ? 'font-weight-bold' : ''}}">25</a>, 
              <a href="size=50" class="page text-dark {{isset($_GET['size']) && $_GET['size'] == 50 ? 'font-weight-bold' : ''}}">50</a>,
              <a href="size=100" class="page text-dark {{isset($_GET['size']) && $_GET['size'] == 100 ? 'font-weight-bold' : ''}}">100</a>
            </span>
            <div class="float-right">
  
              @if ($cars->hasPages())
                  {{ $cars->appends(Request::except('page'))->links() }}
              @endif
            </div>
        </div>
      </div>     
</div>
@endsection